Repository openshift/machine-api-provider-azure, pull requests merged in 2022-06, with the labels that each got.

#22 Bug 2093044: update getAvailabilitySetName function
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, lgtm, approved

#26 Bug 2082667: Bump MAPI dependency. Separate node drain controller.
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/drain_controller.go
  vendor/modules.txt
Labels: bugzilla/severity-high, bugzilla/valid-bug, lgtm, approved

#24 Enable configuration of boot diagnostics when creating VMs
  go.mod
  go.sum
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved
