Repository openshift/machine-api-provider-azure, pull requests merged in 2023-10, with the labels that each got.

#77 OCPBUGS-20268: update bad url endpoint termination handler test
  pkg/termination/termination_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#79 Update OWNERS
  OWNERS
Labels: lgtm, approved

#82 [release-4.12] OCPBUGS-22247,OCPBUGS-19549: Fix empty clusterName references for GenerateMachinePublicIPName
  Makefile
  hack/ci-test.sh
  hack/goimports.sh
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine_scope.go
  pkg/cloud/azure/actuators/machine_scope_test.go
Labels: qe-approved, backport-risk-assessed, cherry-pick-approved, lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
