Repository openshift/machine-api-provider-azure, pull requests merged in 2023-06, with the labels that each got.

#56 OCPBUGS-10762: Machine should be Failed if Machine has a Failed state on Azure
  pkg/cloud/azure/actuators/machine/actuator.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: qe-approved, bugzilla/valid-bug, lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#65 MIXEDARCH-257: Handle the kubernetes.io/architecture label based on the Azure VM Size
  go.mod
  go.sum
  pkg/cloud/azure/actuators/machineset/controller.go
  pkg/cloud/azure/actuators/machineset/controller_test.go
  pkg/cloud/azure/services/resourceskus/sku.go
  vendor/github.com/openshift/machine-api-operator/pkg/util/util.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#66 Set upstream labels and fix capability for the arch-aware scale from 0 in Azure
  pkg/cloud/azure/actuators/machineset/controller.go
  pkg/cloud/azure/services/resourceskus/sku.go
Labels: lgtm, approved
