Repository openshift/machine-api-provider-azure, pull requests merged in 2024-02, with the labels that each got.

#91 OCPBUGS-25940: Don't create availability set when using spot instances
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: qe-approved, backport-risk-assessed, lgtm, approved, jira/valid-bug, jira/valid-reference

#96 OCPBUGS-28745: Improving performance of VMs created in Azure
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  vendor/github.com/openshift/api/config/v1/feature_gates.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: backport-risk-assessed, cherry-pick-approved, lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#97 [release-4.12] OCPBUGS-24564: Reduce cardinality
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: backport-risk-assessed, cherry-pick-approved, lgtm, approved, jira/valid-bug, jira/valid-reference

#99 OCPBUGS-28309: add an extra vendor exclude to snyk config
  .snyk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
